portfolio_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: Adamma12#
      dbname: portfolio
      schema: public
      port: 5432
