version: 2

models:
  - name: stg_stock_prices
    description: "staging table of daily stock prices and tickers, dates and volume"
    columns:
      - name: ticker
        tests:
          - not_null
          - unique
      - name: date
        tests:
          - not_null

  - name: fct_stock_prices
    description:  "fact table of daily stock prices"
    columns:
      - name: date
        tests:
          - not_null
      - name: close
        tests:
          - not_null
